version: "3.9"
services:
  nginx:
    container_name: nginx
    build:
      context: ./requirements/nginx
      args: 
        - DOMAIN_NAME
    depends_on:
      - wordpress
    ports:
      - "443:443"
    networks:
      - network
    restart: always
    volumes:
      - wordpress_data:/var/www/html

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    depends_on:
      - mariadb
    networks:
      - network
    restart: always
    env_file: .env
    volumes:
      - wordpress_data:/var/www/html
  mariadb:
    container_name: mariadb
    build:
      context: ./requirements/mariadb
      args:
          - MYSQL_DATABASE
          - MYSQL_ROOT
          - MYSQL_ROOT_PASSWORD
          - MYSQL_USER
          - MYSQL_PASSWORD
    networks:
      - network
    restart: always
    volumes:
      - mariadb:/var/lib/mysql

volumes:
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      device: /home/llima-ce/data/wordpress
      o: bind
  mariadb:
    driver: local
    driver_opts:
      type: none
      device: /home/llima-ce/data/mariadb
      o: bind

networks:
  network:
