version: "3.9"
name: inception
services:
  site:
    container_name: site
    build: ./bonus/site
    networks:
      - mynetwork
    restart: always
    volumes:
      - wordpress:/var/www/wordpress

  redis:
    container_name: redis
    build: ./bonus/redis
    networks:
      - mynetwork
    restart: always
    depends_on:
      - wordpress

  nginx:
    container_name: nginx
    build:
      context: ./requirements/nginx
      args: 
        - DOMAIN_NAME
    depends_on:
      - wordpress
    ports:
      - "443:443"
    networks:
      - mynetwork
    restart: always
    volumes:
      - wordpress:/var/www/wordpress
  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    depends_on:
      - mariadb
    networks:
      - mynetwork
    restart: always
    env_file: .env
    volumes:
      - wordpress:/var/www/wordpress
  mariadb:
    container_name: mariadb
    build:
      context: ./requirements/mariadb
      args:
          - MYSQL_DATABASE
          - MYSQL_ROOT
          - MYSQL_ROOT_PASSWORD
          - MYSQL_USER
          - MYSQL_USER_PASSWORD
    networks:
      - mynetwork
    restart: always
    env_file: .env
    volumes:
      - mariadb:/var/lib/mysql

volumes:
  wordpress:
    driver: local
    driver_opts:
      type: none
      device: /home/llima-ce/data/wordpress
      o: bind
    name: wordpress

  mariadb:
    driver: local
    driver_opts:
      type: none
      device: /home/llima-ce/data/mariadb
      o: bind
    name: mariadb

networks:
  mynetwork:
    driver: bridge
